@startuml
CLIENT -> api : {data, user}
note over CLIENT, api : data? 처리를 위해 사용된다.\nuser? 퍼미션 처리에 사용된다.
CLIENT <-- api : throw if permission error
api -> store : {...data, ...user?}
CLIENT <-- api : throw if error
CLIENT <- api : result
@enduml
