name: master
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install
        run: npm ci
      - name: tsc
        run: npm run test.tsc
      - name: test
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set AWS credentials
        run: |
          aws configure set region ap-northeast-2
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure --profile yiguana set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure --profile yiguana set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: build yiguana
        run: |
          npm ci
          npm run prepare
      - name: deploy frontend
        run: |
          cd example/web/frontend
          npm ci
          npm run build
          npm run deploy.aws
          cd -
      - name: deploy backend
        run: |
          cd example/web/backend
          npm ci
          npm run deploy
          cd -
