name: terraform
on:
  push:
    branches:
      - master
    paths:
      - '__tests__/e2e/terraform/**'
      - '.github/workflows/*terraform.yml'
jobs:
  update-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set AWS credentials
        run: |
          aws configure set region ap-northeast-2
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure --profile yiguana set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure --profile yiguana set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: deploy
        run: |
          cd __tests__/e2e
          terraform init
          npm run terraform.plan
          npm run terraform.apply
